services:
  db:
    image: brenonakad/intern-sql-challenges:1.0
    container_name: intern_challenges_db
    environment:
      POSTGRES_USER: intern
      POSTGRES_PASSWORD: intern
      POSTGRES_DB: intern_challenges
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: